package com.lj.demo.model;

public class Login {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login.id
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login.userid
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login.starttime
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	private String starttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login.lastaccesstime
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	private String lastaccesstime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column login.host
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	private String host;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login.id
	 * @return  the value of login.id
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login.id
	 * @param id  the value for login.id
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login.userid
	 * @return  the value of login.userid
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login.userid
	 * @param userid  the value for login.userid
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login.starttime
	 * @return  the value of login.starttime
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	public String getStarttime() {
		return starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login.starttime
	 * @param starttime  the value for login.starttime
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login.lastaccesstime
	 * @return  the value of login.lastaccesstime
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	public String getLastaccesstime() {
		return lastaccesstime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login.lastaccesstime
	 * @param lastaccesstime  the value for login.lastaccesstime
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	public void setLastaccesstime(String lastaccesstime) {
		this.lastaccesstime = lastaccesstime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column login.host
	 * @return  the value of login.host
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	public String getHost() {
		return host;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column login.host
	 * @param host  the value for login.host
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	public void setHost(String host) {
		this.host = host;
	}
    
}