package com.lj.demo.model;

public class Permission {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.id
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.dir
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	private String dir;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.page
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	private String page;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.operate
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	private String operate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.stateid
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	private Integer stateid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permission.name
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.id
	 * @return  the value of permission.id
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.id
	 * @param id  the value for permission.id
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.dir
	 * @return  the value of permission.dir
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	public String getDir() {
		return dir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.dir
	 * @param dir  the value for permission.dir
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	public void setDir(String dir) {
		this.dir = dir;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.page
	 * @return  the value of permission.page
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	public String getPage() {
		return page;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.page
	 * @param page  the value for permission.page
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	public void setPage(String page) {
		this.page = page;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.operate
	 * @return  the value of permission.operate
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	public String getOperate() {
		return operate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.operate
	 * @param operate  the value for permission.operate
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	public void setOperate(String operate) {
		this.operate = operate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.stateid
	 * @return  the value of permission.stateid
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	public Integer getStateid() {
		return stateid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.stateid
	 * @param stateid  the value for permission.stateid
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	public void setStateid(Integer stateid) {
		this.stateid = stateid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permission.name
	 * @return  the value of permission.name
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permission.name
	 * @param name  the value for permission.name
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	private String state;

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}
}