package com.lj.demo.model;

public class RolePermission {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_permission.id
	 * @mbg.generated  Thu Sep 21 17:49:21 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_permission.permissionids
	 * @mbg.generated  Thu Sep 21 17:49:21 CST 2017
	 */
	private String permissionids;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_permission.roleid
	 * @mbg.generated  Thu Sep 21 17:49:21 CST 2017
	 */
	private Integer roleid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_permission.id
	 * @return  the value of role_permission.id
	 * @mbg.generated  Thu Sep 21 17:49:21 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_permission.id
	 * @param id  the value for role_permission.id
	 * @mbg.generated  Thu Sep 21 17:49:21 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_permission.permissionids
	 * @return  the value of role_permission.permissionids
	 * @mbg.generated  Thu Sep 21 17:49:21 CST 2017
	 */
	public String getPermissionids() {
		return permissionids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_permission.permissionids
	 * @param permissionids  the value for role_permission.permissionids
	 * @mbg.generated  Thu Sep 21 17:49:21 CST 2017
	 */
	public void setPermissionids(String permissionids) {
		this.permissionids = permissionids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_permission.roleid
	 * @return  the value of role_permission.roleid
	 * @mbg.generated  Thu Sep 21 17:49:21 CST 2017
	 */
	public Integer getRoleid() {
		return roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_permission.roleid
	 * @param roleid  the value for role_permission.roleid
	 * @mbg.generated  Thu Sep 21 17:49:21 CST 2017
	 */
	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	public String permissionnames;
    public String rolename;

	public String getPermissionnames() {
		return permissionnames;
	}

	public void setPermissionnames(String permissionnames) {
		this.permissionnames = permissionnames;
	}

	public String getRolename() {
		return rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}
}