package com.lj.demo.model;

public class State {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column state.id
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column state.state
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	private String state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column state.id
	 * @return  the value of state.id
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column state.id
	 * @param id  the value for state.id
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column state.state
	 * @return  the value of state.state
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column state.state
	 * @param state  the value for state.state
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public void setState(String state) {
		this.state = state;
	}
}