package com.lj.demo.model;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.roleid
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	private Integer roleid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.stateid
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	private Integer stateid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.mail
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	private String mail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.telphone
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	private String telphone;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
	 * @return  the value of user.name
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
	 * @param name  the value for user.name
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.roleid
	 * @return  the value of user.roleid
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public Integer getRoleid() {
		return roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.roleid
	 * @param roleid  the value for user.roleid
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.stateid
	 * @return  the value of user.stateid
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public Integer getStateid() {
		return stateid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.stateid
	 * @param stateid  the value for user.stateid
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public void setStateid(Integer stateid) {
		this.stateid = stateid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.mail
	 * @return  the value of user.mail
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public String getMail() {
		return mail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.mail
	 * @param mail  the value for user.mail
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public void setMail(String mail) {
		this.mail = mail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.telphone
	 * @return  the value of user.telphone
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public String getTelphone() {
		return telphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.telphone
	 * @param telphone  the value for user.telphone
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	public void setTelphone(String telphone) {
		this.telphone = telphone;
	}
	
	private String role;
	private String state;

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}
}