package com.web.badminton.dao;

import com.web.badminton.model.Changdi;
import com.web.badminton.model.ChangdiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChangdiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table changdi
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    long countByExample(ChangdiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table changdi
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    int deleteByExample(ChangdiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table changdi
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table changdi
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    int insert(Changdi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table changdi
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    int insertSelective(Changdi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table changdi
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    List<Changdi> selectByExample(ChangdiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table changdi
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    Changdi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table changdi
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") Changdi record, @Param("example") ChangdiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table changdi
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    int updateByExample(@Param("record") Changdi record, @Param("example") ChangdiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table changdi
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    int updateByPrimaryKeySelective(Changdi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table changdi
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    int updateByPrimaryKey(Changdi record);
}