package com.web.badminton.dao;

import com.web.badminton.model.PayRecord;
import com.web.badminton.model.PayRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payrecord
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    long countByExample(PayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payrecord
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    int deleteByExample(PayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payrecord
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payrecord
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    int insert(PayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payrecord
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    int insertSelective(PayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payrecord
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    List<PayRecord> selectByExample(PayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payrecord
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    PayRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payrecord
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") PayRecord record, @Param("example") PayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payrecord
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    int updateByExample(@Param("record") PayRecord record, @Param("example") PayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payrecord
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    int updateByPrimaryKeySelective(PayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payrecord
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    int updateByPrimaryKey(PayRecord record);
}