package com.web.badminton.dao;

import com.web.badminton.model.Pingjia;
import com.web.badminton.model.PingjiaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PingjiaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    long countByExample(PingjiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    int deleteByExample(PingjiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    int insert(Pingjia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    int insertSelective(Pingjia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    List<Pingjia> selectByExample(PingjiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    Pingjia selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") Pingjia record, @Param("example") PingjiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    int updateByExample(@Param("record") Pingjia record, @Param("example") PingjiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    int updateByPrimaryKeySelective(Pingjia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    int updateByPrimaryKey(Pingjia record);
    
    List<Pingjia> selectbyscore();
}