package com.web.badminton.dao;

import com.web.badminton.model.Root;
import com.web.badminton.model.RootExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RootMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table root
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	long countByExample(RootExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table root
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	int deleteByExample(RootExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table root
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table root
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	int insert(Root record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table root
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	int insertSelective(Root record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table root
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	List<Root> selectByExample(RootExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table root
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	Root selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table root
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Root record, @Param("example") RootExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table root
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	int updateByExample(@Param("record") Root record, @Param("example") RootExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table root
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	int updateByPrimaryKeySelective(Root record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table root
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	int updateByPrimaryKey(Root record);
}