package com.web.badminton.dao;

import com.web.badminton.model.Xinwen;
import com.web.badminton.model.XinwenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XinwenMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinwen
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	long countByExample(XinwenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinwen
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	int deleteByExample(XinwenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinwen
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinwen
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	int insert(Xinwen record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinwen
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	int insertSelective(Xinwen record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinwen
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	List<Xinwen> selectByExample(XinwenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinwen
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	Xinwen selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinwen
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Xinwen record, @Param("example") XinwenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinwen
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	int updateByExample(@Param("record") Xinwen record, @Param("example") XinwenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinwen
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	int updateByPrimaryKeySelective(Xinwen record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinwen
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	int updateByPrimaryKey(Xinwen record);
	
}