package com.web.order.dao;

import com.web.order.model.Cp;
import com.web.order.model.CpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cp
	 * @mbg.generated  Mon Mar 27 23:58:48 CST 2017
	 */
	long countByExample(CpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cp
	 * @mbg.generated  Mon Mar 27 23:58:48 CST 2017
	 */
	int deleteByExample(CpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cp
	 * @mbg.generated  Mon Mar 27 23:58:48 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cp
	 * @mbg.generated  Mon Mar 27 23:58:48 CST 2017
	 */
	int insert(Cp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cp
	 * @mbg.generated  Mon Mar 27 23:58:48 CST 2017
	 */
	int insertSelective(Cp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cp
	 * @mbg.generated  Mon Mar 27 23:58:48 CST 2017
	 */
	List<Cp> selectByExample(CpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cp
	 * @mbg.generated  Mon Mar 27 23:58:48 CST 2017
	 */
	Cp selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cp
	 * @mbg.generated  Mon Mar 27 23:58:48 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Cp record, @Param("example") CpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cp
	 * @mbg.generated  Mon Mar 27 23:58:48 CST 2017
	 */
	int updateByExample(@Param("record") Cp record, @Param("example") CpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cp
	 * @mbg.generated  Mon Mar 27 23:58:48 CST 2017
	 */
	int updateByPrimaryKeySelective(Cp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_cp
	 * @mbg.generated  Mon Mar 27 23:58:48 CST 2017
	 */
	int updateByPrimaryKey(Cp record);
}