package com.web.order.model;

public class Cp {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cp.id
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cp.typeid
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	private Integer typeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cp.goodsname
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	private String goodsname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cp.introduce
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	private String introduce;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cp.price
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cp.nowprice
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	private Double nowprice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cp.picture
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	private String picture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cp.intime
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	private String intime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_cp.newgoods
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	private Integer newgoods;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cp.id
	 * @return  the value of t_cp.id
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cp.id
	 * @param id  the value for t_cp.id
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cp.typeid
	 * @return  the value of t_cp.typeid
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	public Integer getTypeid() {
		return typeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cp.typeid
	 * @param typeid  the value for t_cp.typeid
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	public void setTypeid(Integer typeid) {
		this.typeid = typeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cp.goodsname
	 * @return  the value of t_cp.goodsname
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	public String getGoodsname() {
		return goodsname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cp.goodsname
	 * @param goodsname  the value for t_cp.goodsname
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	public void setGoodsname(String goodsname) {
		this.goodsname = goodsname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cp.introduce
	 * @return  the value of t_cp.introduce
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	public String getIntroduce() {
		return introduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cp.introduce
	 * @param introduce  the value for t_cp.introduce
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	public void setIntroduce(String introduce) {
		this.introduce = introduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cp.price
	 * @return  the value of t_cp.price
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cp.price
	 * @param price  the value for t_cp.price
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cp.nowprice
	 * @return  the value of t_cp.nowprice
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	public Double getNowprice() {
		return nowprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cp.nowprice
	 * @param nowprice  the value for t_cp.nowprice
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	public void setNowprice(Double nowprice) {
		this.nowprice = nowprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cp.picture
	 * @return  the value of t_cp.picture
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	public String getPicture() {
		return picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cp.picture
	 * @param picture  the value for t_cp.picture
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	public void setPicture(String picture) {
		this.picture = picture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cp.intime
	 * @return  the value of t_cp.intime
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	public String getIntime() {
		return intime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cp.intime
	 * @param intime  the value for t_cp.intime
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	public void setIntime(String intime) {
		this.intime = intime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_cp.newgoods
	 * @return  the value of t_cp.newgoods
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	public Integer getNewgoods() {
		return newgoods;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_cp.newgoods
	 * @param newgoods  the value for t_cp.newgoods
	 * @mbg.generated  Thu Mar 09 01:00:55 CST 2017
	 */
	public void setNewgoods(Integer newgoods) {
		this.newgoods = newgoods;
	}
}