package com.web.order.model;

public class Notice {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notice.id
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notice.title
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notice.content
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notice.pic
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	private String pic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notice.shopid
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	private Integer shopid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notice.id
	 * @return  the value of t_notice.id
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notice.id
	 * @param id  the value for t_notice.id
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notice.title
	 * @return  the value of t_notice.title
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notice.title
	 * @param title  the value for t_notice.title
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notice.content
	 * @return  the value of t_notice.content
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notice.content
	 * @param content  the value for t_notice.content
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notice.pic
	 * @return  the value of t_notice.pic
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public String getPic() {
		return pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notice.pic
	 * @param pic  the value for t_notice.pic
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void setPic(String pic) {
		this.pic = pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notice.shopid
	 * @return  the value of t_notice.shopid
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public Integer getShopid() {
		return shopid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notice.shopid
	 * @param shopid  the value for t_notice.shopid
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void setShopid(Integer shopid) {
		this.shopid = shopid;
	}
}