package com.web.order.model;

import java.util.ArrayList;
import java.util.List;

public class OrderExample extends BaseExample{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_order
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_order
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_order
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public OrderExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_order
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("username is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("username is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("username =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("username <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("username >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("username >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("username <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("username <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("username like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("username not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("username in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("username not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("username between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("username not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andOrderdataIsNull() {
			addCriterion("orderdata is null");
			return (Criteria) this;
		}

		public Criteria andOrderdataIsNotNull() {
			addCriterion("orderdata is not null");
			return (Criteria) this;
		}

		public Criteria andOrderdataEqualTo(String value) {
			addCriterion("orderdata =", value, "orderdata");
			return (Criteria) this;
		}

		public Criteria andOrderdataNotEqualTo(String value) {
			addCriterion("orderdata <>", value, "orderdata");
			return (Criteria) this;
		}

		public Criteria andOrderdataGreaterThan(String value) {
			addCriterion("orderdata >", value, "orderdata");
			return (Criteria) this;
		}

		public Criteria andOrderdataGreaterThanOrEqualTo(String value) {
			addCriterion("orderdata >=", value, "orderdata");
			return (Criteria) this;
		}

		public Criteria andOrderdataLessThan(String value) {
			addCriterion("orderdata <", value, "orderdata");
			return (Criteria) this;
		}

		public Criteria andOrderdataLessThanOrEqualTo(String value) {
			addCriterion("orderdata <=", value, "orderdata");
			return (Criteria) this;
		}

		public Criteria andOrderdataLike(String value) {
			addCriterion("orderdata like", value, "orderdata");
			return (Criteria) this;
		}

		public Criteria andOrderdataNotLike(String value) {
			addCriterion("orderdata not like", value, "orderdata");
			return (Criteria) this;
		}

		public Criteria andOrderdataIn(List<String> values) {
			addCriterion("orderdata in", values, "orderdata");
			return (Criteria) this;
		}

		public Criteria andOrderdataNotIn(List<String> values) {
			addCriterion("orderdata not in", values, "orderdata");
			return (Criteria) this;
		}

		public Criteria andOrderdataBetween(String value1, String value2) {
			addCriterion("orderdata between", value1, value2, "orderdata");
			return (Criteria) this;
		}

		public Criteria andOrderdataNotBetween(String value1, String value2) {
			addCriterion("orderdata not between", value1, value2, "orderdata");
			return (Criteria) this;
		}

		public Criteria andEnforceIsNull() {
			addCriterion("enforce is null");
			return (Criteria) this;
		}

		public Criteria andEnforceIsNotNull() {
			addCriterion("enforce is not null");
			return (Criteria) this;
		}

		public Criteria andEnforceEqualTo(Integer value) {
			addCriterion("enforce =", value, "enforce");
			return (Criteria) this;
		}

		public Criteria andEnforceNotEqualTo(Integer value) {
			addCriterion("enforce <>", value, "enforce");
			return (Criteria) this;
		}

		public Criteria andEnforceGreaterThan(Integer value) {
			addCriterion("enforce >", value, "enforce");
			return (Criteria) this;
		}

		public Criteria andEnforceGreaterThanOrEqualTo(Integer value) {
			addCriterion("enforce >=", value, "enforce");
			return (Criteria) this;
		}

		public Criteria andEnforceLessThan(Integer value) {
			addCriterion("enforce <", value, "enforce");
			return (Criteria) this;
		}

		public Criteria andEnforceLessThanOrEqualTo(Integer value) {
			addCriterion("enforce <=", value, "enforce");
			return (Criteria) this;
		}

		public Criteria andEnforceIn(List<Integer> values) {
			addCriterion("enforce in", values, "enforce");
			return (Criteria) this;
		}

		public Criteria andEnforceNotIn(List<Integer> values) {
			addCriterion("enforce not in", values, "enforce");
			return (Criteria) this;
		}

		public Criteria andEnforceBetween(Integer value1, Integer value2) {
			addCriterion("enforce between", value1, value2, "enforce");
			return (Criteria) this;
		}

		public Criteria andEnforceNotBetween(Integer value1, Integer value2) {
			addCriterion("enforce not between", value1, value2, "enforce");
			return (Criteria) this;
		}

		public Criteria andBzIsNull() {
			addCriterion("bz is null");
			return (Criteria) this;
		}

		public Criteria andBzIsNotNull() {
			addCriterion("bz is not null");
			return (Criteria) this;
		}

		public Criteria andBzEqualTo(String value) {
			addCriterion("bz =", value, "bz");
			return (Criteria) this;
		}

		public Criteria andBzNotEqualTo(String value) {
			addCriterion("bz <>", value, "bz");
			return (Criteria) this;
		}

		public Criteria andBzGreaterThan(String value) {
			addCriterion("bz >", value, "bz");
			return (Criteria) this;
		}

		public Criteria andBzGreaterThanOrEqualTo(String value) {
			addCriterion("bz >=", value, "bz");
			return (Criteria) this;
		}

		public Criteria andBzLessThan(String value) {
			addCriterion("bz <", value, "bz");
			return (Criteria) this;
		}

		public Criteria andBzLessThanOrEqualTo(String value) {
			addCriterion("bz <=", value, "bz");
			return (Criteria) this;
		}

		public Criteria andBzLike(String value) {
			addCriterion("bz like", value, "bz");
			return (Criteria) this;
		}

		public Criteria andBzNotLike(String value) {
			addCriterion("bz not like", value, "bz");
			return (Criteria) this;
		}

		public Criteria andBzIn(List<String> values) {
			addCriterion("bz in", values, "bz");
			return (Criteria) this;
		}

		public Criteria andBzNotIn(List<String> values) {
			addCriterion("bz not in", values, "bz");
			return (Criteria) this;
		}

		public Criteria andBzBetween(String value1, String value2) {
			addCriterion("bz between", value1, value2, "bz");
			return (Criteria) this;
		}

		public Criteria andBzNotBetween(String value1, String value2) {
			addCriterion("bz not between", value1, value2, "bz");
			return (Criteria) this;
		}

		public Criteria andIspayIsNull() {
			addCriterion("ispay is null");
			return (Criteria) this;
		}

		public Criteria andIspayIsNotNull() {
			addCriterion("ispay is not null");
			return (Criteria) this;
		}

		public Criteria andIspayEqualTo(Integer value) {
			addCriterion("ispay =", value, "ispay");
			return (Criteria) this;
		}

		public Criteria andIspayNotEqualTo(Integer value) {
			addCriterion("ispay <>", value, "ispay");
			return (Criteria) this;
		}

		public Criteria andIspayGreaterThan(Integer value) {
			addCriterion("ispay >", value, "ispay");
			return (Criteria) this;
		}

		public Criteria andIspayGreaterThanOrEqualTo(Integer value) {
			addCriterion("ispay >=", value, "ispay");
			return (Criteria) this;
		}

		public Criteria andIspayLessThan(Integer value) {
			addCriterion("ispay <", value, "ispay");
			return (Criteria) this;
		}

		public Criteria andIspayLessThanOrEqualTo(Integer value) {
			addCriterion("ispay <=", value, "ispay");
			return (Criteria) this;
		}

		public Criteria andIspayIn(List<Integer> values) {
			addCriterion("ispay in", values, "ispay");
			return (Criteria) this;
		}

		public Criteria andIspayNotIn(List<Integer> values) {
			addCriterion("ispay not in", values, "ispay");
			return (Criteria) this;
		}

		public Criteria andIspayBetween(Integer value1, Integer value2) {
			addCriterion("ispay between", value1, value2, "ispay");
			return (Criteria) this;
		}

		public Criteria andIspayNotBetween(Integer value1, Integer value2) {
			addCriterion("ispay not between", value1, value2, "ispay");
			return (Criteria) this;
		}

		public Criteria andCpnameIsNull() {
			addCriterion("cpname is null");
			return (Criteria) this;
		}

		public Criteria andCpnameIsNotNull() {
			addCriterion("cpname is not null");
			return (Criteria) this;
		}

		public Criteria andCpnameEqualTo(String value) {
			addCriterion("cpname =", value, "cpname");
			return (Criteria) this;
		}

		public Criteria andCpnameNotEqualTo(String value) {
			addCriterion("cpname <>", value, "cpname");
			return (Criteria) this;
		}

		public Criteria andCpnameGreaterThan(String value) {
			addCriterion("cpname >", value, "cpname");
			return (Criteria) this;
		}

		public Criteria andCpnameGreaterThanOrEqualTo(String value) {
			addCriterion("cpname >=", value, "cpname");
			return (Criteria) this;
		}

		public Criteria andCpnameLessThan(String value) {
			addCriterion("cpname <", value, "cpname");
			return (Criteria) this;
		}

		public Criteria andCpnameLessThanOrEqualTo(String value) {
			addCriterion("cpname <=", value, "cpname");
			return (Criteria) this;
		}

		public Criteria andCpnameLike(String value) {
			addCriterion("cpname like", value, "cpname");
			return (Criteria) this;
		}

		public Criteria andCpnameNotLike(String value) {
			addCriterion("cpname not like", value, "cpname");
			return (Criteria) this;
		}

		public Criteria andCpnameIn(List<String> values) {
			addCriterion("cpname in", values, "cpname");
			return (Criteria) this;
		}

		public Criteria andCpnameNotIn(List<String> values) {
			addCriterion("cpname not in", values, "cpname");
			return (Criteria) this;
		}

		public Criteria andCpnameBetween(String value1, String value2) {
			addCriterion("cpname between", value1, value2, "cpname");
			return (Criteria) this;
		}

		public Criteria andCpnameNotBetween(String value1, String value2) {
			addCriterion("cpname not between", value1, value2, "cpname");
			return (Criteria) this;
		}

		public Criteria andNumIsNull() {
			addCriterion("num is null");
			return (Criteria) this;
		}

		public Criteria andNumIsNotNull() {
			addCriterion("num is not null");
			return (Criteria) this;
		}

		public Criteria andNumEqualTo(String value) {
			addCriterion("num =", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotEqualTo(String value) {
			addCriterion("num <>", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumGreaterThan(String value) {
			addCriterion("num >", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumGreaterThanOrEqualTo(String value) {
			addCriterion("num >=", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLessThan(String value) {
			addCriterion("num <", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLessThanOrEqualTo(String value) {
			addCriterion("num <=", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLike(String value) {
			addCriterion("num like", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotLike(String value) {
			addCriterion("num not like", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumIn(List<String> values) {
			addCriterion("num in", values, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotIn(List<String> values) {
			addCriterion("num not in", values, "num");
			return (Criteria) this;
		}

		public Criteria andNumBetween(String value1, String value2) {
			addCriterion("num between", value1, value2, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotBetween(String value1, String value2) {
			addCriterion("num not between", value1, value2, "num");
			return (Criteria) this;
		}

		public Criteria andTimeIsNull() {
			addCriterion("time is null");
			return (Criteria) this;
		}

		public Criteria andTimeIsNotNull() {
			addCriterion("time is not null");
			return (Criteria) this;
		}

		public Criteria andTimeEqualTo(String value) {
			addCriterion("time =", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotEqualTo(String value) {
			addCriterion("time <>", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThan(String value) {
			addCriterion("time >", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThanOrEqualTo(String value) {
			addCriterion("time >=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThan(String value) {
			addCriterion("time <", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThanOrEqualTo(String value) {
			addCriterion("time <=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLike(String value) {
			addCriterion("time like", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotLike(String value) {
			addCriterion("time not like", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeIn(List<String> values) {
			addCriterion("time in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotIn(List<String> values) {
			addCriterion("time not in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeBetween(String value1, String value2) {
			addCriterion("time between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotBetween(String value1, String value2) {
			addCriterion("time not between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andShopidIsNull() {
			addCriterion("shopid is null");
			return (Criteria) this;
		}

		public Criteria andShopidIsNotNull() {
			addCriterion("shopid is not null");
			return (Criteria) this;
		}

		public Criteria andShopidEqualTo(Integer value) {
			addCriterion("shopid =", value, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidNotEqualTo(Integer value) {
			addCriterion("shopid <>", value, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidGreaterThan(Integer value) {
			addCriterion("shopid >", value, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidGreaterThanOrEqualTo(Integer value) {
			addCriterion("shopid >=", value, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidLessThan(Integer value) {
			addCriterion("shopid <", value, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidLessThanOrEqualTo(Integer value) {
			addCriterion("shopid <=", value, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidIn(List<Integer> values) {
			addCriterion("shopid in", values, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidNotIn(List<Integer> values) {
			addCriterion("shopid not in", values, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidBetween(Integer value1, Integer value2) {
			addCriterion("shopid between", value1, value2, "shopid");
			return (Criteria) this;
		}

		public Criteria andShopidNotBetween(Integer value1, Integer value2) {
			addCriterion("shopid not between", value1, value2, "shopid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_order
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order
     *
     * @mbg.generated do_not_delete_during_merge Sun Mar 05 00:12:42 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}