package com.web.order.model;

public class Order {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.id
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.username
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.orderdata
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	private String orderdata;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.enforce
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	private Integer enforce;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.bz
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	private String bz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.ispay
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	private Integer ispay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.cpname
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	private String cpname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.num
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	private String num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.time
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	private String time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.shopid
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	private Integer shopid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.id
	 * @return  the value of t_order.id
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.id
	 * @param id  the value for t_order.id
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.username
	 * @return  the value of t_order.username
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.username
	 * @param username  the value for t_order.username
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.orderdata
	 * @return  the value of t_order.orderdata
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public String getOrderdata() {
		return orderdata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.orderdata
	 * @param orderdata  the value for t_order.orderdata
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void setOrderdata(String orderdata) {
		this.orderdata = orderdata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.enforce
	 * @return  the value of t_order.enforce
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public Integer getEnforce() {
		return enforce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.enforce
	 * @param enforce  the value for t_order.enforce
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void setEnforce(Integer enforce) {
		this.enforce = enforce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.bz
	 * @return  the value of t_order.bz
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public String getBz() {
		return bz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.bz
	 * @param bz  the value for t_order.bz
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void setBz(String bz) {
		this.bz = bz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.ispay
	 * @return  the value of t_order.ispay
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public Integer getIspay() {
		return ispay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.ispay
	 * @param ispay  the value for t_order.ispay
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void setIspay(Integer ispay) {
		this.ispay = ispay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.cpname
	 * @return  the value of t_order.cpname
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public String getCpname() {
		return cpname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.cpname
	 * @param cpname  the value for t_order.cpname
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void setCpname(String cpname) {
		this.cpname = cpname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.num
	 * @return  the value of t_order.num
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public String getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.num
	 * @param num  the value for t_order.num
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void setNum(String num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.time
	 * @return  the value of t_order.time
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public String getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.time
	 * @param time  the value for t_order.time
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void setTime(String time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.shopid
	 * @return  the value of t_order.shopid
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public Integer getShopid() {
		return shopid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.shopid
	 * @param shopid  the value for t_order.shopid
	 * @mbg.generated  Sat Mar 25 13:25:55 CST 2017
	 */
	public void setShopid(Integer shopid) {
		this.shopid = shopid;
	}
}