package com.web.order.model;

public class ShopCar {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_shopcar.id
	 * @mbg.generated  Wed Mar 22 22:49:34 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_shopcar.cpname
	 * @mbg.generated  Wed Mar 22 22:49:34 CST 2017
	 */
	private String cpname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_shopcar.username
	 * @mbg.generated  Wed Mar 22 22:49:34 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_shopcar.num
	 * @mbg.generated  Wed Mar 22 22:49:34 CST 2017
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_shopcar.price
	 * @mbg.generated  Wed Mar 22 22:49:34 CST 2017
	 */
	private Integer price;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_shopcar.id
	 * @return  the value of t_shopcar.id
	 * @mbg.generated  Wed Mar 22 22:49:34 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_shopcar.id
	 * @param id  the value for t_shopcar.id
	 * @mbg.generated  Wed Mar 22 22:49:34 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_shopcar.cpname
	 * @return  the value of t_shopcar.cpname
	 * @mbg.generated  Wed Mar 22 22:49:34 CST 2017
	 */
	public String getCpname() {
		return cpname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_shopcar.cpname
	 * @param cpname  the value for t_shopcar.cpname
	 * @mbg.generated  Wed Mar 22 22:49:34 CST 2017
	 */
	public void setCpname(String cpname) {
		this.cpname = cpname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_shopcar.username
	 * @return  the value of t_shopcar.username
	 * @mbg.generated  Wed Mar 22 22:49:34 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_shopcar.username
	 * @param username  the value for t_shopcar.username
	 * @mbg.generated  Wed Mar 22 22:49:34 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_shopcar.num
	 * @return  the value of t_shopcar.num
	 * @mbg.generated  Wed Mar 22 22:49:34 CST 2017
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_shopcar.num
	 * @param num  the value for t_shopcar.num
	 * @mbg.generated  Wed Mar 22 22:49:34 CST 2017
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_shopcar.price
	 * @return  the value of t_shopcar.price
	 * @mbg.generated  Wed Mar 22 22:49:34 CST 2017
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_shopcar.price
	 * @param price  the value for t_shopcar.price
	 * @mbg.generated  Wed Mar 22 22:49:34 CST 2017
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}
}