package com.web.order.model;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop.id
     *
     * @mbg.generated Sat Mar 25 13:25:55 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop.shopname
     *
     * @mbg.generated Sat Mar 25 13:25:55 CST 2017
     */
    private String shopname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop.introduce
     *
     * @mbg.generated Sat Mar 25 13:25:55 CST 2017
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shop.pic
     *
     * @mbg.generated Sat Mar 25 13:25:55 CST 2017
     */
    private String pic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop.id
     *
     * @return the value of t_shop.id
     *
     * @mbg.generated Sat Mar 25 13:25:55 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop.id
     *
     * @param id the value for t_shop.id
     *
     * @mbg.generated Sat Mar 25 13:25:55 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop.shopname
     *
     * @return the value of t_shop.shopname
     *
     * @mbg.generated Sat Mar 25 13:25:55 CST 2017
     */
    public String getShopname() {
        return shopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop.shopname
     *
     * @param shopname the value for t_shop.shopname
     *
     * @mbg.generated Sat Mar 25 13:25:55 CST 2017
     */
    public void setShopname(String shopname) {
        this.shopname = shopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop.introduce
     *
     * @return the value of t_shop.introduce
     *
     * @mbg.generated Sat Mar 25 13:25:55 CST 2017
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop.introduce
     *
     * @param introduce the value for t_shop.introduce
     *
     * @mbg.generated Sat Mar 25 13:25:55 CST 2017
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shop.pic
     *
     * @return the value of t_shop.pic
     *
     * @mbg.generated Sat Mar 25 13:25:55 CST 2017
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shop.pic
     *
     * @param pic the value for t_shop.pic
     *
     * @mbg.generated Sat Mar 25 13:25:55 CST 2017
     */
    public void setPic(String pic) {
        this.pic = pic;
    }
}