package com.web.order.model;

public class Message {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_message.id
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_message.username
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_message.phone
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_message.content
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_message.reply
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private String reply;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_message.id
	 * @return  the value of t_message.id
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_message.id
	 * @param id  the value for t_message.id
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_message.username
	 * @return  the value of t_message.username
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_message.username
	 * @param username  the value for t_message.username
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_message.phone
	 * @return  the value of t_message.phone
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_message.phone
	 * @param phone  the value for t_message.phone
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_message.content
	 * @return  the value of t_message.content
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_message.content
	 * @param content  the value for t_message.content
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_message.reply
	 * @return  the value of t_message.reply
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public String getReply() {
		return reply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_message.reply
	 * @param reply  the value for t_message.reply
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setReply(String reply) {
		this.reply = reply;
	}
}