package com.web.order.model;

public class Notice {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notice.id
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notice.title
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notice.content
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_notice.intime
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private String intime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notice.id
	 * @return  the value of t_notice.id
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notice.id
	 * @param id  the value for t_notice.id
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notice.title
	 * @return  the value of t_notice.title
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notice.title
	 * @param title  the value for t_notice.title
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notice.content
	 * @return  the value of t_notice.content
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notice.content
	 * @param content  the value for t_notice.content
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_notice.intime
	 * @return  the value of t_notice.intime
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public String getIntime() {
		return intime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_notice.intime
	 * @param intime  the value for t_notice.intime
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setIntime(String intime) {
		this.intime = intime;
	}
}