package com.web.order.model;

public class ShopCar {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_shopcar.id
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_shopcar.cpid
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private Integer cpid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_shopcar.userid
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private Integer userid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_shopcar.id
	 * @return  the value of t_shopcar.id
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_shopcar.id
	 * @param id  the value for t_shopcar.id
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_shopcar.cpid
	 * @return  the value of t_shopcar.cpid
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public Integer getCpid() {
		return cpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_shopcar.cpid
	 * @param cpid  the value for t_shopcar.cpid
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setCpid(Integer cpid) {
		this.cpid = cpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_shopcar.userid
	 * @return  the value of t_shopcar.userid
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_shopcar.userid
	 * @param userid  the value for t_shopcar.userid
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}
}