package com.web.order.model;

public class Vote {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vote.id
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vote.username
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vote.cpid
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private Integer cpid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vote.sjid
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private Integer sjid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vote.ztpj
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private String ztpj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vote.title
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vote.rj
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private String rj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vote.content
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vote.bq
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private String bq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_vote.bz
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private String bz;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vote.id
	 * @return  the value of t_vote.id
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vote.id
	 * @param id  the value for t_vote.id
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vote.username
	 * @return  the value of t_vote.username
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vote.username
	 * @param username  the value for t_vote.username
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vote.cpid
	 * @return  the value of t_vote.cpid
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public Integer getCpid() {
		return cpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vote.cpid
	 * @param cpid  the value for t_vote.cpid
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setCpid(Integer cpid) {
		this.cpid = cpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vote.sjid
	 * @return  the value of t_vote.sjid
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public Integer getSjid() {
		return sjid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vote.sjid
	 * @param sjid  the value for t_vote.sjid
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setSjid(Integer sjid) {
		this.sjid = sjid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vote.ztpj
	 * @return  the value of t_vote.ztpj
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public String getZtpj() {
		return ztpj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vote.ztpj
	 * @param ztpj  the value for t_vote.ztpj
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setZtpj(String ztpj) {
		this.ztpj = ztpj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vote.title
	 * @return  the value of t_vote.title
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vote.title
	 * @param title  the value for t_vote.title
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vote.rj
	 * @return  the value of t_vote.rj
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public String getRj() {
		return rj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vote.rj
	 * @param rj  the value for t_vote.rj
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setRj(String rj) {
		this.rj = rj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vote.content
	 * @return  the value of t_vote.content
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vote.content
	 * @param content  the value for t_vote.content
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vote.bq
	 * @return  the value of t_vote.bq
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public String getBq() {
		return bq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vote.bq
	 * @param bq  the value for t_vote.bq
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setBq(String bq) {
		this.bq = bq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_vote.bz
	 * @return  the value of t_vote.bz
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public String getBz() {
		return bz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_vote.bz
	 * @param bz  the value for t_vote.bz
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setBz(String bz) {
		this.bz = bz;
	}
}