package com.web.badminton.model;

public class Changdi {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column changdi.id
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column changdi.name
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column changdi.address
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column changdi.telphone
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column changdi.admin
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    private String admin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column changdi.introduce
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column changdi.route
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    private String route;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column changdi.pic
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column changdi.price
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    private Float price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column changdi.id
     *
     * @return the value of changdi.id
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column changdi.id
     *
     * @param id the value for changdi.id
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column changdi.name
     *
     * @return the value of changdi.name
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column changdi.name
     *
     * @param name the value for changdi.name
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column changdi.address
     *
     * @return the value of changdi.address
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column changdi.address
     *
     * @param address the value for changdi.address
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column changdi.telphone
     *
     * @return the value of changdi.telphone
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column changdi.telphone
     *
     * @param telphone the value for changdi.telphone
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column changdi.admin
     *
     * @return the value of changdi.admin
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public String getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column changdi.admin
     *
     * @param admin the value for changdi.admin
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public void setAdmin(String admin) {
        this.admin = admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column changdi.introduce
     *
     * @return the value of changdi.introduce
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column changdi.introduce
     *
     * @param introduce the value for changdi.introduce
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column changdi.route
     *
     * @return the value of changdi.route
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public String getRoute() {
        return route;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column changdi.route
     *
     * @param route the value for changdi.route
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public void setRoute(String route) {
        this.route = route;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column changdi.pic
     *
     * @return the value of changdi.pic
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column changdi.pic
     *
     * @param pic the value for changdi.pic
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column changdi.price
     *
     * @return the value of changdi.price
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column changdi.price
     *
     * @param price the value for changdi.price
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public void setPrice(Float price) {
        this.price = price;
    }
}