package com.web.badminton.model;

public class Dingdan {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dingdan.id
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dingdan.changdiid
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	private Integer changdiid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dingdan.userid
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dingdan.playtime
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	private String playtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dingdan.time
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	private Float time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dingdan.starttime
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	private String starttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dingdan.endtime
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	private String endtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dingdan.id
	 * @return  the value of dingdan.id
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dingdan.id
	 * @param id  the value for dingdan.id
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dingdan.changdiid
	 * @return  the value of dingdan.changdiid
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	public Integer getChangdiid() {
		return changdiid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dingdan.changdiid
	 * @param changdiid  the value for dingdan.changdiid
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	public void setChangdiid(Integer changdiid) {
		this.changdiid = changdiid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dingdan.userid
	 * @return  the value of dingdan.userid
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dingdan.userid
	 * @param userid  the value for dingdan.userid
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dingdan.playtime
	 * @return  the value of dingdan.playtime
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	public String getPlaytime() {
		return playtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dingdan.playtime
	 * @param playtime  the value for dingdan.playtime
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	public void setPlaytime(String playtime) {
		this.playtime = playtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dingdan.time
	 * @return  the value of dingdan.time
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	public Float getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dingdan.time
	 * @param time  the value for dingdan.time
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	public void setTime(Float time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dingdan.starttime
	 * @return  the value of dingdan.starttime
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	public String getStarttime() {
		return starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dingdan.starttime
	 * @param starttime  the value for dingdan.starttime
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dingdan.endtime
	 * @return  the value of dingdan.endtime
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	public String getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dingdan.endtime
	 * @param endtime  the value for dingdan.endtime
	 * @mbg.generated  Thu May 25 18:05:35 CST 2017
	 */
	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}
}