package com.web.badminton.model;

public class PayRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payrecord.id
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payrecord.userid
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payrecord.time
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payrecord.money
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    private Float money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payrecord.id
     *
     * @return the value of payrecord.id
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payrecord.id
     *
     * @param id the value for payrecord.id
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payrecord.userid
     *
     * @return the value of payrecord.userid
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payrecord.userid
     *
     * @param userid the value for payrecord.userid
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payrecord.time
     *
     * @return the value of payrecord.time
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payrecord.time
     *
     * @param time the value for payrecord.time
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payrecord.money
     *
     * @return the value of payrecord.money
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payrecord.money
     *
     * @param money the value for payrecord.money
     *
     * @mbg.generated Fri May 19 14:12:28 CST 2017
     */
    public void setMoney(Float money) {
        this.money = money;
    }
}