package com.web.badminton.model;

public class Pingjia {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingjia.id
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingjia.changdiid
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    private Integer changdiid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingjia.score
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingjia.pingjia
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    private String pingjia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingjia.userid
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pingjia.time
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingjia.id
     *
     * @return the value of pingjia.id
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingjia.id
     *
     * @param id the value for pingjia.id
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingjia.changdiid
     *
     * @return the value of pingjia.changdiid
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public Integer getChangdiid() {
        return changdiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingjia.changdiid
     *
     * @param changdiid the value for pingjia.changdiid
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public void setChangdiid(Integer changdiid) {
        this.changdiid = changdiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingjia.score
     *
     * @return the value of pingjia.score
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingjia.score
     *
     * @param score the value for pingjia.score
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingjia.pingjia
     *
     * @return the value of pingjia.pingjia
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public String getPingjia() {
        return pingjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingjia.pingjia
     *
     * @param pingjia the value for pingjia.pingjia
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public void setPingjia(String pingjia) {
        this.pingjia = pingjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingjia.userid
     *
     * @return the value of pingjia.userid
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingjia.userid
     *
     * @param userid the value for pingjia.userid
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pingjia.time
     *
     * @return the value of pingjia.time
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pingjia.time
     *
     * @param time the value for pingjia.time
     *
     * @mbg.generated Tue May 16 23:29:25 CST 2017
     */
    public void setTime(String time) {
        this.time = time;
    }
}