package com.web.badminton.model;

public class Root {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column root.id
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column root.username
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column root.password
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column root.realname
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	private String realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column root.telphone
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	private String telphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column root.pic
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	private String pic;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column root.id
	 * @return  the value of root.id
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column root.id
	 * @param id  the value for root.id
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column root.username
	 * @return  the value of root.username
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column root.username
	 * @param username  the value for root.username
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column root.password
	 * @return  the value of root.password
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column root.password
	 * @param password  the value for root.password
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column root.realname
	 * @return  the value of root.realname
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column root.realname
	 * @param realname  the value for root.realname
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column root.telphone
	 * @return  the value of root.telphone
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	public String getTelphone() {
		return telphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column root.telphone
	 * @param telphone  the value for root.telphone
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	public void setTelphone(String telphone) {
		this.telphone = telphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column root.pic
	 * @return  the value of root.pic
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	public String getPic() {
		return pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column root.pic
	 * @param pic  the value for root.pic
	 * @mbg.generated  Tue May 16 23:49:12 CST 2017
	 */
	public void setPic(String pic) {
		this.pic = pic;
	}
}