package com.web.badminton.model;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbg.generated  Wed May 17 23:17:04 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbg.generated  Wed May 17 23:17:04 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbg.generated  Wed May 17 23:17:04 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.realname
	 * @mbg.generated  Wed May 17 23:17:04 CST 2017
	 */
	private String realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.telphone
	 * @mbg.generated  Wed May 17 23:17:04 CST 2017
	 */
	private String telphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.money
	 * @mbg.generated  Wed May 17 23:17:04 CST 2017
	 */
	private Float money;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbg.generated  Wed May 17 23:17:04 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbg.generated  Wed May 17 23:17:04 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbg.generated  Wed May 17 23:17:04 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbg.generated  Wed May 17 23:17:04 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbg.generated  Wed May 17 23:17:04 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbg.generated  Wed May 17 23:17:04 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.realname
	 * @return  the value of user.realname
	 * @mbg.generated  Wed May 17 23:17:04 CST 2017
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.realname
	 * @param realname  the value for user.realname
	 * @mbg.generated  Wed May 17 23:17:04 CST 2017
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.telphone
	 * @return  the value of user.telphone
	 * @mbg.generated  Wed May 17 23:17:04 CST 2017
	 */
	public String getTelphone() {
		return telphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.telphone
	 * @param telphone  the value for user.telphone
	 * @mbg.generated  Wed May 17 23:17:04 CST 2017
	 */
	public void setTelphone(String telphone) {
		this.telphone = telphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.money
	 * @return  the value of user.money
	 * @mbg.generated  Wed May 17 23:17:04 CST 2017
	 */
	public Float getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.money
	 * @param money  the value for user.money
	 * @mbg.generated  Wed May 17 23:17:04 CST 2017
	 */
	public void setMoney(Float money) {
		this.money = money;
	}
}