package com.web.badminton.model;

public class Xinwen {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinwen.id
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinwen.title
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinwen.content
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinwen.time
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	private String time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinwen.pic
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	private String pic;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinwen.id
	 * @return  the value of xinwen.id
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinwen.id
	 * @param id  the value for xinwen.id
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinwen.title
	 * @return  the value of xinwen.title
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinwen.title
	 * @param title  the value for xinwen.title
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinwen.content
	 * @return  the value of xinwen.content
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinwen.content
	 * @param content  the value for xinwen.content
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinwen.time
	 * @return  the value of xinwen.time
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	public String getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinwen.time
	 * @param time  the value for xinwen.time
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	public void setTime(String time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinwen.pic
	 * @return  the value of xinwen.pic
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	public String getPic() {
		return pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinwen.pic
	 * @param pic  the value for xinwen.pic
	 * @mbg.generated  Sat May 20 01:48:18 CST 2017
	 */
	public void setPic(String pic) {
		this.pic = pic;
	}
}