package com.web.order.model;

public class Information {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_information.id
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_information.title
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_information.content
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_information.time
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	private String time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_information.id
	 * @return  the value of t_information.id
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_information.id
	 * @param id  the value for t_information.id
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_information.title
	 * @return  the value of t_information.title
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_information.title
	 * @param title  the value for t_information.title
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_information.content
	 * @return  the value of t_information.content
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_information.content
	 * @param content  the value for t_information.content
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_information.time
	 * @return  the value of t_information.time
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public String getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_information.time
	 * @param time  the value for t_information.time
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setTime(String time) {
		this.time = time;
	}
}