package com.web.order.model;

import java.util.ArrayList;
import java.util.List;

public class VoteExample extends BaseExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public VoteExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("username is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("username is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("username =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("username <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("username >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("username >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("username <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("username <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("username like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("username not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("username in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("username not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("username between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("username not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andCpidIsNull() {
			addCriterion("cpid is null");
			return (Criteria) this;
		}

		public Criteria andCpidIsNotNull() {
			addCriterion("cpid is not null");
			return (Criteria) this;
		}

		public Criteria andCpidEqualTo(Integer value) {
			addCriterion("cpid =", value, "cpid");
			return (Criteria) this;
		}

		public Criteria andCpidNotEqualTo(Integer value) {
			addCriterion("cpid <>", value, "cpid");
			return (Criteria) this;
		}

		public Criteria andCpidGreaterThan(Integer value) {
			addCriterion("cpid >", value, "cpid");
			return (Criteria) this;
		}

		public Criteria andCpidGreaterThanOrEqualTo(Integer value) {
			addCriterion("cpid >=", value, "cpid");
			return (Criteria) this;
		}

		public Criteria andCpidLessThan(Integer value) {
			addCriterion("cpid <", value, "cpid");
			return (Criteria) this;
		}

		public Criteria andCpidLessThanOrEqualTo(Integer value) {
			addCriterion("cpid <=", value, "cpid");
			return (Criteria) this;
		}

		public Criteria andCpidIn(List<Integer> values) {
			addCriterion("cpid in", values, "cpid");
			return (Criteria) this;
		}

		public Criteria andCpidNotIn(List<Integer> values) {
			addCriterion("cpid not in", values, "cpid");
			return (Criteria) this;
		}

		public Criteria andCpidBetween(Integer value1, Integer value2) {
			addCriterion("cpid between", value1, value2, "cpid");
			return (Criteria) this;
		}

		public Criteria andCpidNotBetween(Integer value1, Integer value2) {
			addCriterion("cpid not between", value1, value2, "cpid");
			return (Criteria) this;
		}

		public Criteria andSjidIsNull() {
			addCriterion("sjid is null");
			return (Criteria) this;
		}

		public Criteria andSjidIsNotNull() {
			addCriterion("sjid is not null");
			return (Criteria) this;
		}

		public Criteria andSjidEqualTo(Integer value) {
			addCriterion("sjid =", value, "sjid");
			return (Criteria) this;
		}

		public Criteria andSjidNotEqualTo(Integer value) {
			addCriterion("sjid <>", value, "sjid");
			return (Criteria) this;
		}

		public Criteria andSjidGreaterThan(Integer value) {
			addCriterion("sjid >", value, "sjid");
			return (Criteria) this;
		}

		public Criteria andSjidGreaterThanOrEqualTo(Integer value) {
			addCriterion("sjid >=", value, "sjid");
			return (Criteria) this;
		}

		public Criteria andSjidLessThan(Integer value) {
			addCriterion("sjid <", value, "sjid");
			return (Criteria) this;
		}

		public Criteria andSjidLessThanOrEqualTo(Integer value) {
			addCriterion("sjid <=", value, "sjid");
			return (Criteria) this;
		}

		public Criteria andSjidIn(List<Integer> values) {
			addCriterion("sjid in", values, "sjid");
			return (Criteria) this;
		}

		public Criteria andSjidNotIn(List<Integer> values) {
			addCriterion("sjid not in", values, "sjid");
			return (Criteria) this;
		}

		public Criteria andSjidBetween(Integer value1, Integer value2) {
			addCriterion("sjid between", value1, value2, "sjid");
			return (Criteria) this;
		}

		public Criteria andSjidNotBetween(Integer value1, Integer value2) {
			addCriterion("sjid not between", value1, value2, "sjid");
			return (Criteria) this;
		}

		public Criteria andZtpjIsNull() {
			addCriterion("ztpj is null");
			return (Criteria) this;
		}

		public Criteria andZtpjIsNotNull() {
			addCriterion("ztpj is not null");
			return (Criteria) this;
		}

		public Criteria andZtpjEqualTo(String value) {
			addCriterion("ztpj =", value, "ztpj");
			return (Criteria) this;
		}

		public Criteria andZtpjNotEqualTo(String value) {
			addCriterion("ztpj <>", value, "ztpj");
			return (Criteria) this;
		}

		public Criteria andZtpjGreaterThan(String value) {
			addCriterion("ztpj >", value, "ztpj");
			return (Criteria) this;
		}

		public Criteria andZtpjGreaterThanOrEqualTo(String value) {
			addCriterion("ztpj >=", value, "ztpj");
			return (Criteria) this;
		}

		public Criteria andZtpjLessThan(String value) {
			addCriterion("ztpj <", value, "ztpj");
			return (Criteria) this;
		}

		public Criteria andZtpjLessThanOrEqualTo(String value) {
			addCriterion("ztpj <=", value, "ztpj");
			return (Criteria) this;
		}

		public Criteria andZtpjLike(String value) {
			addCriterion("ztpj like", value, "ztpj");
			return (Criteria) this;
		}

		public Criteria andZtpjNotLike(String value) {
			addCriterion("ztpj not like", value, "ztpj");
			return (Criteria) this;
		}

		public Criteria andZtpjIn(List<String> values) {
			addCriterion("ztpj in", values, "ztpj");
			return (Criteria) this;
		}

		public Criteria andZtpjNotIn(List<String> values) {
			addCriterion("ztpj not in", values, "ztpj");
			return (Criteria) this;
		}

		public Criteria andZtpjBetween(String value1, String value2) {
			addCriterion("ztpj between", value1, value2, "ztpj");
			return (Criteria) this;
		}

		public Criteria andZtpjNotBetween(String value1, String value2) {
			addCriterion("ztpj not between", value1, value2, "ztpj");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andRjIsNull() {
			addCriterion("rj is null");
			return (Criteria) this;
		}

		public Criteria andRjIsNotNull() {
			addCriterion("rj is not null");
			return (Criteria) this;
		}

		public Criteria andRjEqualTo(String value) {
			addCriterion("rj =", value, "rj");
			return (Criteria) this;
		}

		public Criteria andRjNotEqualTo(String value) {
			addCriterion("rj <>", value, "rj");
			return (Criteria) this;
		}

		public Criteria andRjGreaterThan(String value) {
			addCriterion("rj >", value, "rj");
			return (Criteria) this;
		}

		public Criteria andRjGreaterThanOrEqualTo(String value) {
			addCriterion("rj >=", value, "rj");
			return (Criteria) this;
		}

		public Criteria andRjLessThan(String value) {
			addCriterion("rj <", value, "rj");
			return (Criteria) this;
		}

		public Criteria andRjLessThanOrEqualTo(String value) {
			addCriterion("rj <=", value, "rj");
			return (Criteria) this;
		}

		public Criteria andRjLike(String value) {
			addCriterion("rj like", value, "rj");
			return (Criteria) this;
		}

		public Criteria andRjNotLike(String value) {
			addCriterion("rj not like", value, "rj");
			return (Criteria) this;
		}

		public Criteria andRjIn(List<String> values) {
			addCriterion("rj in", values, "rj");
			return (Criteria) this;
		}

		public Criteria andRjNotIn(List<String> values) {
			addCriterion("rj not in", values, "rj");
			return (Criteria) this;
		}

		public Criteria andRjBetween(String value1, String value2) {
			addCriterion("rj between", value1, value2, "rj");
			return (Criteria) this;
		}

		public Criteria andRjNotBetween(String value1, String value2) {
			addCriterion("rj not between", value1, value2, "rj");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("content is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("content is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("content =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("content <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("content >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("content >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("content <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("content <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("content like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("content not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("content in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("content not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("content between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("content not between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andBqIsNull() {
			addCriterion("bq is null");
			return (Criteria) this;
		}

		public Criteria andBqIsNotNull() {
			addCriterion("bq is not null");
			return (Criteria) this;
		}

		public Criteria andBqEqualTo(String value) {
			addCriterion("bq =", value, "bq");
			return (Criteria) this;
		}

		public Criteria andBqNotEqualTo(String value) {
			addCriterion("bq <>", value, "bq");
			return (Criteria) this;
		}

		public Criteria andBqGreaterThan(String value) {
			addCriterion("bq >", value, "bq");
			return (Criteria) this;
		}

		public Criteria andBqGreaterThanOrEqualTo(String value) {
			addCriterion("bq >=", value, "bq");
			return (Criteria) this;
		}

		public Criteria andBqLessThan(String value) {
			addCriterion("bq <", value, "bq");
			return (Criteria) this;
		}

		public Criteria andBqLessThanOrEqualTo(String value) {
			addCriterion("bq <=", value, "bq");
			return (Criteria) this;
		}

		public Criteria andBqLike(String value) {
			addCriterion("bq like", value, "bq");
			return (Criteria) this;
		}

		public Criteria andBqNotLike(String value) {
			addCriterion("bq not like", value, "bq");
			return (Criteria) this;
		}

		public Criteria andBqIn(List<String> values) {
			addCriterion("bq in", values, "bq");
			return (Criteria) this;
		}

		public Criteria andBqNotIn(List<String> values) {
			addCriterion("bq not in", values, "bq");
			return (Criteria) this;
		}

		public Criteria andBqBetween(String value1, String value2) {
			addCriterion("bq between", value1, value2, "bq");
			return (Criteria) this;
		}

		public Criteria andBqNotBetween(String value1, String value2) {
			addCriterion("bq not between", value1, value2, "bq");
			return (Criteria) this;
		}

		public Criteria andBzIsNull() {
			addCriterion("bz is null");
			return (Criteria) this;
		}

		public Criteria andBzIsNotNull() {
			addCriterion("bz is not null");
			return (Criteria) this;
		}

		public Criteria andBzEqualTo(String value) {
			addCriterion("bz =", value, "bz");
			return (Criteria) this;
		}

		public Criteria andBzNotEqualTo(String value) {
			addCriterion("bz <>", value, "bz");
			return (Criteria) this;
		}

		public Criteria andBzGreaterThan(String value) {
			addCriterion("bz >", value, "bz");
			return (Criteria) this;
		}

		public Criteria andBzGreaterThanOrEqualTo(String value) {
			addCriterion("bz >=", value, "bz");
			return (Criteria) this;
		}

		public Criteria andBzLessThan(String value) {
			addCriterion("bz <", value, "bz");
			return (Criteria) this;
		}

		public Criteria andBzLessThanOrEqualTo(String value) {
			addCriterion("bz <=", value, "bz");
			return (Criteria) this;
		}

		public Criteria andBzLike(String value) {
			addCriterion("bz like", value, "bz");
			return (Criteria) this;
		}

		public Criteria andBzNotLike(String value) {
			addCriterion("bz not like", value, "bz");
			return (Criteria) this;
		}

		public Criteria andBzIn(List<String> values) {
			addCriterion("bz in", values, "bz");
			return (Criteria) this;
		}

		public Criteria andBzNotIn(List<String> values) {
			addCriterion("bz not in", values, "bz");
			return (Criteria) this;
		}

		public Criteria andBzBetween(String value1, String value2) {
			addCriterion("bz between", value1, value2, "bz");
			return (Criteria) this;
		}

		public Criteria andBzNotBetween(String value1, String value2) {
			addCriterion("bz not between", value1, value2, "bz");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_vote
     *
     * @mbg.generated do_not_delete_during_merge Sat Mar 04 21:52:54 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}