package com.web.order.dao;

import com.web.order.model.Notice;
import com.web.order.model.NoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoticeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	long countByExample(NoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int deleteByExample(NoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int insert(Notice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int insertSelective(Notice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	List<Notice> selectByExample(NoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	Notice selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Notice record, @Param("example") NoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int updateByExample(@Param("record") Notice record, @Param("example") NoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int updateByPrimaryKeySelective(Notice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_notice
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int updateByPrimaryKey(Notice record);
}