package com.web.order.dao;

import com.web.order.model.Order;
import com.web.order.model.OrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Mar 08 21:52:34 CST 2017
	 */
	long countByExample(OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Mar 08 21:52:34 CST 2017
	 */
	int deleteByExample(OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Mar 08 21:52:34 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Mar 08 21:52:34 CST 2017
	 */
	int insert(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Mar 08 21:52:34 CST 2017
	 */
	int insertSelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Mar 08 21:52:34 CST 2017
	 */
	List<Order> selectByExample(OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Mar 08 21:52:34 CST 2017
	 */
	Order selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Mar 08 21:52:34 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Mar 08 21:52:34 CST 2017
	 */
	int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Mar 08 21:52:34 CST 2017
	 */
	int updateByPrimaryKeySelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbg.generated  Wed Mar 08 21:52:34 CST 2017
	 */
	int updateByPrimaryKey(Order record);
}