package com.web.order.dao;

import com.web.order.model.ShopCar;
import com.web.order.model.ShopCarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopCarMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_shopcar
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	long countByExample(ShopCarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_shopcar
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int deleteByExample(ShopCarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_shopcar
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_shopcar
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int insert(ShopCar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_shopcar
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int insertSelective(ShopCar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_shopcar
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	List<ShopCar> selectByExample(ShopCarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_shopcar
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	ShopCar selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_shopcar
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int updateByExampleSelective(@Param("record") ShopCar record, @Param("example") ShopCarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_shopcar
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int updateByExample(@Param("record") ShopCar record, @Param("example") ShopCarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_shopcar
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int updateByPrimaryKeySelective(ShopCar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_shopcar
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int updateByPrimaryKey(ShopCar record);
}