package com.web.order.model;

public class MyCp {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mycp.id
	 * @mbg.generated  Thu Mar 23 15:53:41 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mycp.cpname
	 * @mbg.generated  Thu Mar 23 15:53:41 CST 2017
	 */
	private String cpname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mycp.username
	 * @mbg.generated  Thu Mar 23 15:53:41 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mycp.price
	 * @mbg.generated  Thu Mar 23 15:53:41 CST 2017
	 */
	private String price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mycp.pic
	 * @mbg.generated  Thu Mar 23 15:53:41 CST 2017
	 */
	private String pic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mycp.name
	 * @mbg.generated  Thu Mar 23 15:53:41 CST 2017
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mycp.id
	 * @return  the value of t_mycp.id
	 * @mbg.generated  Thu Mar 23 15:53:41 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mycp.id
	 * @param id  the value for t_mycp.id
	 * @mbg.generated  Thu Mar 23 15:53:41 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mycp.cpname
	 * @return  the value of t_mycp.cpname
	 * @mbg.generated  Thu Mar 23 15:53:41 CST 2017
	 */
	public String getCpname() {
		return cpname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mycp.cpname
	 * @param cpname  the value for t_mycp.cpname
	 * @mbg.generated  Thu Mar 23 15:53:41 CST 2017
	 */
	public void setCpname(String cpname) {
		this.cpname = cpname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mycp.username
	 * @return  the value of t_mycp.username
	 * @mbg.generated  Thu Mar 23 15:53:41 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mycp.username
	 * @param username  the value for t_mycp.username
	 * @mbg.generated  Thu Mar 23 15:53:41 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mycp.price
	 * @return  the value of t_mycp.price
	 * @mbg.generated  Thu Mar 23 15:53:41 CST 2017
	 */
	public String getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mycp.price
	 * @param price  the value for t_mycp.price
	 * @mbg.generated  Thu Mar 23 15:53:41 CST 2017
	 */
	public void setPrice(String price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mycp.pic
	 * @return  the value of t_mycp.pic
	 * @mbg.generated  Thu Mar 23 15:53:41 CST 2017
	 */
	public String getPic() {
		return pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mycp.pic
	 * @param pic  the value for t_mycp.pic
	 * @mbg.generated  Thu Mar 23 15:53:41 CST 2017
	 */
	public void setPic(String pic) {
		this.pic = pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mycp.name
	 * @return  the value of t_mycp.name
	 * @mbg.generated  Thu Mar 23 15:53:41 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mycp.name
	 * @param name  the value for t_mycp.name
	 * @mbg.generated  Thu Mar 23 15:53:41 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}
}