package com.web.order.dao;

import com.web.order.model.Message;
import com.web.order.model.MessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_message
	 * @mbg.generated  Sat Mar 25 15:02:11 CST 2017
	 */
	long countByExample(MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_message
	 * @mbg.generated  Sat Mar 25 15:02:11 CST 2017
	 */
	int deleteByExample(MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_message
	 * @mbg.generated  Sat Mar 25 15:02:11 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_message
	 * @mbg.generated  Sat Mar 25 15:02:11 CST 2017
	 */
	int insert(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_message
	 * @mbg.generated  Sat Mar 25 15:02:11 CST 2017
	 */
	int insertSelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_message
	 * @mbg.generated  Sat Mar 25 15:02:11 CST 2017
	 */
	List<Message> selectByExample(MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_message
	 * @mbg.generated  Sat Mar 25 15:02:11 CST 2017
	 */
	Message selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_message
	 * @mbg.generated  Sat Mar 25 15:02:11 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Message record, @Param("example") MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_message
	 * @mbg.generated  Sat Mar 25 15:02:11 CST 2017
	 */
	int updateByExample(@Param("record") Message record, @Param("example") MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_message
	 * @mbg.generated  Sat Mar 25 15:02:11 CST 2017
	 */
	int updateByPrimaryKeySelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_message
	 * @mbg.generated  Sat Mar 25 15:02:11 CST 2017
	 */
	int updateByPrimaryKey(Message record);
}