package com.web.order.dao;

import com.web.order.model.Vote;
import com.web.order.model.VoteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	long countByExample(VoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int deleteByExample(VoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int insert(Vote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int insertSelective(Vote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	List<Vote> selectByExample(VoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	Vote selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Vote record, @Param("example") VoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int updateByExample(@Param("record") Vote record, @Param("example") VoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int updateByPrimaryKeySelective(Vote record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_vote
	 * @mbg.generated  Mon Mar 06 00:15:07 CST 2017
	 */
	int updateByPrimaryKey(Vote record);
}