package com.lj.demo.dao;

import com.lj.demo.model.Login;
import com.lj.demo.model.LoginExample;
import java.util.List;
import java.util.Set;

import org.apache.ibatis.annotations.Param;

public interface LoginMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	long countByExample(LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	int deleteByExample(LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	int insert(Login record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	int insertSelective(Login record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	List<Login> selectByExample(LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	Login selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Login record, @Param("example") LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	int updateByExample(@Param("record") Login record, @Param("example") LoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	int updateByPrimaryKeySelective(Login record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table login
	 * @mbg.generated  Tue Sep 12 17:28:19 CST 2017
	 */
	int updateByPrimaryKey(Login record);

	Set<String> getRoles(String telphone);
}