package com.lj.demo.dao;

import com.lj.demo.model.Permission;
import com.lj.demo.model.PermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	long countByExample(PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	int deleteByExample(PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	int insert(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	int insertSelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	List<Permission> selectByExample(PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	Permission selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Permission record, @Param("example") PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	int updateByExample(@Param("record") Permission record, @Param("example") PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	int updateByPrimaryKeySelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 * @mbg.generated  Thu Sep 21 17:19:28 CST 2017
	 */
	int updateByPrimaryKey(Permission record);
}