package com.lj.demo.dao;

import com.lj.demo.model.State;
import com.lj.demo.model.StateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table state
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	long countByExample(StateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table state
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	int deleteByExample(StateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table state
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table state
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	int insert(State record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table state
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	int insertSelective(State record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table state
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	List<State> selectByExample(StateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table state
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	State selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table state
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	int updateByExampleSelective(@Param("record") State record, @Param("example") StateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table state
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	int updateByExample(@Param("record") State record, @Param("example") StateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table state
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	int updateByPrimaryKeySelective(State record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table state
	 * @mbg.generated  Mon Aug 28 14:37:17 CST 2017
	 */
	int updateByPrimaryKey(State record);
	
	int selectIdByState(String name);
}